<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>PHP template</title>
        <style>
            body {
              min-width: 400px;
              max-width: 70%;
              margin-left: auto;
              margin-right: auto;
              font-size: 24px;
              font-family: Verdana, Geneva, Tahoma, sans-serif;
            }
        </style>
    </head>
    <body>
        <h1>PHP template</h1>
        <p>Welcome! Here's a message that's just part of the HTML document</p>
        <p>And this message was generated by PHP at Mon Apr 10, 2023 13:15</p>
    </body>
</html>
